# Generated by Django 4.0 on 2022-01-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_blog',
            name='phone',
        ),
        migrations.AddField(
            model_name='comment_blog',
            name='email',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
