# Generated by Django 4.0 on 2022-01-07 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contactmessage_status_alter_order_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_cheff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55)),
                ('email', models.CharField(blank=True, max_length=55)),
                ('comment', models.TextField(blank=True, max_length=255)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud Emas')], default='True', max_length=15)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cheff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chef')),
            ],
        ),
    ]
